### ISSUE TITLE
Readings export as CSV

### ISSUE THREAD

**Issue by GorAlexander** [Rorschach23/TrialProject#5]
This is the extension of the basic task.

The requirement is to add the 'Export Readings' link on the meter's page.
Clicking on the link would call the browser's native save-file pop-up (but no need to reload the page).

The structure of the exported CSV is three columns: date, absolute value, relative value. It is the same as the example table in the task's description "Example of input/output data".

**Comment by Rorschach23** [comment]
Now the template have an extra button that allows to download current meter data in csv file. The file contains three columns as was asked.

**Comment by GorAlexander** [comment]
Hi @Rorschach23 ,

Meter details page fails with:

`
Internal Server Error: /trialProj/m2/
Traceback (most recent call last):
  File "/Users/oleksandr/Pro/TrialProject/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/oleksandr/Pro/TrialProject/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/oleksandr/Pro/TrialProject/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/oleksandr/Pro/TrialProject/trialProjApp/views.py", line 38, in detail
    df.to_csv('trialProjApp/downloads/currentCSV.csv', columns=['ABSOLUTE VALUE', 'DATE', 'RELATIVE VALUE'], index=False)
  File "/Users/oleksandr/Pro/TrialProject/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 3167, in to_csv
    formatter.save()
  File "/Users/oleksandr/Pro/TrialProject/venv/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/Users/oleksandr/Pro/TrialProject/venv/lib/python3.7/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'trialProjApp/downloads/currentCSV.csv'
[08/Aug/2020 10:08:49] "GET /trialProj/m2/ HTTP/1.1" 500 85386
`

Removing the line with df.to_csv(..) fixes page load issue but CSV export won't work then.

Your approach with 'currentCSV.csv' file is not good:
1. the current state build logic runs inside the details view
2. storing the state as a csv file is not necessary
3. currentCSV.csv is common for all the meters. It matters: in the case you open many meter pages only the last one would lead to the correct exported CSV.

The solution is not reliable.

**Comment by Rorschach23** [comment]
It works fine.
How it works now: detail page is loaded -> if meter has any data, application creates(or updates) a csv file with current values which can be loaded by clicking yellow button. True, the file is common for all meters, but it would be the file for current tracker and that covers the task.
![image](https://user-images.githubusercontent.com/7027172/89710312-84814500-d98a-11ea-8620-64b53ecd54a2.png)

**Comment by Rorschach23** [comment]
I've managed to change code so that now data from several tabs could be download independently. Added small bugfix that fixes crash when trying to download csv file while the file is absent. This solution was manually tested, though right now I don't know how to do this without using file.
Also code was rewritten so now it reuses duplicate code which was taken from views to another module.
